[2019-04-19 12:42:33 -0700] [31328] [INFO] Starting gunicorn 19.9.0
[2019-04-19 12:42:33 -0700] [31328] [INFO] Listening at: http://127.0.0.1:8000 (31328)
[2019-04-19 12:42:33 -0700] [31328] [INFO] Using worker: sync
[2019-04-19 12:42:33 -0700] [31331] [INFO] Booting worker with pid: 31331
[2019-04-19 12:42:33 -0700] [31331] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/alejandrogarcia/Desktop/restaurant/django-restaurant/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'src'
[2019-04-19 12:42:33 -0700] [31331] [INFO] Worker exiting (pid: 31331)
[2019-04-19 12:42:33 -0700] [31328] [INFO] Shutting down: Master
[2019-04-19 12:42:33 -0700] [31328] [INFO] Reason: Worker failed to boot.
